#ifndef BINARYHEAPDLL_GLOBAL_H
#define BINARYHEAPDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BINARYHEAPDLL_LIBRARY)
#define BINARYHEAPDLL_EXPORT Q_DECL_EXPORT
#else
#define BINARYHEAPDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // BINARYHEAPDLL_GLOBAL_H
